[birthDate] Adds support for DateTimeImmutable + force data type on setBirthDate
DavidePastore/codice-fiscale pull request #32
Opened 2019-03-27 12:42 UTC by giorgioma

Ciao!
Sto usando DateTimeImmutable al posto di DateTime e veniva ritornato un errore, ho fatto un piccolo update.

Ho anche spostato la logica della conversione del parametro dal `_construct` a `setBirthDate`, poiche' vedo che nel `Checker` viene chiamato cosi'
```
$this->subject->getBirthDate()->format('y');
```

2019-03-27 13:00 UTC, giorgioma commented
**Breaking changes**: DateTimeInterface e' disponibile solo da php>=5.5, mentre Travis ha come supporto minimo php 5.4

2019-03-27 13:40 UTC, DavidePastore commented
Ciao @giorgioma. Grazie per la tua PR. Potresti aggiungere anche un caso di test in cui dimostri che utilizzando una $birthDate con un valore che prima ti dava errore ora funziona invece correttamente?

2019-03-27 14:58 UTC, giorgioma commented
> Ciao @giorgioma. Grazie per la tua PR. Potresti aggiungere anche un caso di test in cui dimostri che utilizzando una $birthDate con un valore che prima ti dava errore ora funziona invece correttamente?

Purtroppo lavoro solo su PHP>7, mentre PHPunit 3.7 (usato su questa libreria) non e' compatibile...
Se non e' un problema ho aggiornato anche la libreria

2019-03-28 21:15 UTC, giorgioma commented
Sinceramente non ho mai lavorato con hhvm  e non saprei come risolvere l'errore sul test...

2019-03-30 12:04 UTC, DavidePastore requested changes
Ottimo lavoro! Ti chiederei di sistemare un paio di cose (ti dovrebbe bastare approvare la mia suggestion):
- eliminare il supporto per hhvm (a quanto pare non è più supportato nemmeno da [Composer](https://github.com/composer/composer/blob/master/.travis.yml));
- aggiungere la build per PHP 7.3 e la nightly di PHP.

2019-03-30 12:04 UTC, DavidePastore commented on .travis.yml
>    - hhvm
```suggestion
   - 7.3
   - nightly
```

2019-05-26 16:47 UTC, DavidePastore approved these changes

2019-05-26 16:48 UTC, merged

2019-05-26 17:00 UTC, DavidePastore commented
Thanks @giorgioma ! You can find the new changes in the latest release: 0.5.0. 🎉🎉🎉