fix warnings
DavidePastore/codice-fiscale pull request #77
Opened 2024-07-26 08:47 UTC by garak

Fix #76

2024-07-26 08:54 UTC, DavidePastore commented
Hi @garak. Could you please also include some tests for it?

2024-07-26 10:03 UTC, garak commented
I just added a test case (and cleaned up tests a bit).
I realized it was my fault in the end, so the case is the same as the other issue I mentioned in mine.
The current test is passing without warnings. If you run the same test on master, you'll get the warnings instead.

The problem, at this point, is that the calculator calculates an invalid cf when passing a shorter belfiore code. The problem is present in master branch too. Let met know if you prefer to merge this PR and wait for a different PR fixing this other problem, or if it's better to fix everything here

2025-02-10 09:48 UTC, DavidePastore commented
Thanks for your PR, @garak. Let's have this fix in another PR.

2025-02-10 09:52 UTC, DavidePastore commented on test/InverseCalculatorTest.php
> +    public function todotestInverseCalculatorDoesNotThrowWarnings(): void
Is the name of the function correct?

2025-02-10 09:55 UTC, DavidePastore requested changes
I left a little comment

2025-02-10 17:31 UTC, garak commented on test/InverseCalculatorTest.php
> +    public function todotestInverseCalculatorDoesNotThrowWarnings(): void
My bad, I renamed it

2025-02-10 17:56 UTC, DavidePastore approved these changes

2025-02-10 17:57 UTC, DavidePastore approved these changes

2025-02-10 17:57 UTC, merged